version: '3.4'

services:
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
